[package]
name = "handy_tcp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tun-tap = { version = "0.1" }
etherparse = {version = "0.13"}
